name: panaroo-CI

# CINTENT >> MANUAL_TRIGGER
# on:
#   push:
#     branches:
#     - master
#     - devel
#   pull_request:
#     branches:
#     - master
#     - devel
#   schedule:
#     - cron:  '1 1 1 * *'
on: [repository_dispatch, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # CINTENT >> REMOVE_MATRIX
        # python-version: ["3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # CINTENT >> INSERT_CINTENT
    - uses: JavidDitty/setup-cintent@3e5b2faf83a2ad32c22a1cd0f86f5f20ea53a5ab

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install cd-hit
        sudo apt-get install mafft
        wget https://github.com/marbl/Mash/releases/download/v2.2/mash-Linux64-v2.2.tar
        tar -xvf mash-Linux64-v2.2.tar
        sudo cp ./mash-Linux64-v2.2/mash /usr/bin/mash
        python --version
        pip install -U pip
        pip install -U pytest
        wget https://github.com/gtonkinhill/panaroo_test_data/releases/download/v0.0.2/travis_test_data.zip
        unzip travis_test_data.zip
        
    - name: Install
      run: pip install .

    - name: Validation Tests
      run: pytest -W ignore -q --datafolder="${{ github.workspace }}/travis_test_data/"

    # CINTENT >> INSERT_CINTENT
    - name: Upload CIntent Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ env.CINTENT_ARTIFACT_NAME }}
        path: ${{ env.CINTENT_LOGS }}